
[[Snippets]]
  Description = "rclone clash VM image to google drive"
  Output = ""
  Tag = ["clash"]
  command = "sudo rclone copy ./hi.img gdrive:VM-images"

[[Snippets]]
  Description = "Start ephemeral neovim container in current directory"
  Output = ""
  Tag = []
  command = "docker run -it --rm -v `pwd`:/mnt/volume --workdir=/mnt/volume anatolelucet/neovim:stable"

[[Snippets]]
  Description = "wake up mac-mini screen"
  Output = ""
  Tag = []
  command = "ssh mac-mini caffeinate -u -t 1"

[[Snippets]]
  Description = "activate VS2022 powershell environment in-shell"
  Output = ""
  Tag = []
  command = "& \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\Launch-VsDevShell.ps1\" -Arch amd64"

[[Snippets]]
  Description = "put mac-mini display to sleep"
  Output = ""
  Tag = []
  command = "ssh mac-mini pmset displaysleepnow"

[[Snippets]]
  Description = "install homebrew"
  Output = ""
  Tag = []
  command = "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""

[[Snippets]]
  Description = "restart plasma shell (doesn't kill any apps)"
  Output = ""
  Tag = []
  command = "kquitapp6 plasmashell; kstart plasmashell"

[[Snippets]]
  Description = "put kde wayland display to sleep"
  Output = ""
  Tag = []
  command = "kscreen-doctor --dpms off"

[[Snippets]]
  Description = "check public ip"
  Output = ""
  Tag = []
  command = "curl https://ipinfo.io/ip"

[[Snippets]]
  Description = "get external IP address"
  Output = ""
  Tag = []
  command = "curl https://ipinfo.io/ip"
